export enum categoryActionTypes {
    GET_CATEGORIES_REQUEST = "GET_CATEGORIES_REQUEST",
    GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS",
    GET_CATEGORIES_FAILURE = "GET_CATEGORIES_FAILURE",
    SELECT_CATEGORY = "SELECT_CATEGORY",
}

export enum jokeActionTypes {
    GET_RANDOM_JOKE_REQUEST = "GET_RANDOM_JOKE_REQUEST",
    GET_RANDOM_JOKE_SUCCESS = "GET_RANDOM_JOKE_SUCCESS",
    GET_RANDOM_JOKE_FAILURE = "GET_RANDOM_JOKE_FAILURE",
    GET_SEARCHED_JOKES_REQUEST = "GET_SEARCHED_JOKES_REQUEST",
    GET_SEARCHED_JOKES_SUCCESS = "GET_SEARCHED_JOKES_SUCCESS",
    GET_SEARCHED_JOKES_FAILURE = "GET_SEARCHED_JOKES_FAILURE",
    GET_JOKE_BY_CATEGORY_REQUEST = "GET_JOKE_BY_CATEGORY_REQUEST",
    GET_JOKE_BY_CATEGORY_SUCCESS = "GET_JOKE_BY_CATEGORY_SUCCESS",
    GET_JOKE_BY_CATEGORY_FAILURE = "GET_JOKE_BY_CATEGORY_FAILURE"

}
